### ISSUE TITLE
After upgrade electron to 2.0.3 os-locale is not working

### ISSUE THREAD

**Issue by jhalehol** [sindresorhus/os-locale#29]
I upgraded my electron application to the version 2.0.3, and after this, I am getting this error

`execa.stdout is not a function ` when I tried use the os-locale library, before it is working with electron 1.7.8

Thanks for your help, regards

**Comment by Ajeey** [comment]
@jhalehol  Is the issue still there?
